import Head from 'next/head'
import React, {useEffect} from "react";
import MainBlock from "../src/blocks/main";

export default function Home() {
    useEffect(() => {

    })
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <MainBlock/>
        </>
    )
}
